#!/bin/bash



mkdir mydir
chmod +x ./mydir
chmod +r ./mydir
chmod +w ./mydir
touch ./mydir/myfile
echo 2023 > ./mydir/myfile
mv moveme ./mydir
cp copyme ./mydir
mv ./mydir/copyme ./mydir/copied
cat readme
gcc bad.c 2>err.txt




